// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDusVvsDTkrMh8T9N7s9YhcoRBvIRzRQEI',
    appId: '1:430598349534:web:98da3aaf67feee8547984f',
    messagingSenderId: '430598349534',
    projectId: 'golfapp-33b10',
    authDomain: 'golfapp-33b10.firebaseapp.com',
    storageBucket: 'golfapp-33b10.firebasestorage.app',
    measurementId: 'G-0W4HKN44NG',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbURs4GIw1KmMSc1zWfwY4DBAZklQKgrc',
    appId: '1:430598349534:android:39499567d582c8ed47984f',
    messagingSenderId: '430598349534',
    projectId: 'golfapp-33b10',
    storageBucket: 'golfapp-33b10.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFsCjF8zD607wDY6VQOKV6XpTAcx71nMc',
    appId: '1:430598349534:ios:c7d8cc41bc37be8347984f',
    messagingSenderId: '430598349534',
    projectId: 'golfapp-33b10',
    storageBucket: 'golfapp-33b10.firebasestorage.app',
    iosBundleId: 'com.example.rickAndMorty',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFsCjF8zD607wDY6VQOKV6XpTAcx71nMc',
    appId: '1:430598349534:ios:c7d8cc41bc37be8347984f',
    messagingSenderId: '430598349534',
    projectId: 'golfapp-33b10',
    storageBucket: 'golfapp-33b10.firebasestorage.app',
    iosBundleId: 'com.example.rickAndMorty',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDusVvsDTkrMh8T9N7s9YhcoRBvIRzRQEI',
    appId: '1:430598349534:web:5f7065e0fdc3f7ba47984f',
    messagingSenderId: '430598349534',
    projectId: 'golfapp-33b10',
    authDomain: 'golfapp-33b10.firebaseapp.com',
    storageBucket: 'golfapp-33b10.firebasestorage.app',
    measurementId: 'G-DMJRVBD8DE',
  );
}
